// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Datagraph: typeof import('./src/components/datagraph.vue')['default']
    Functions: typeof import('./src/components/functions.vue')['default']
    Gismap: typeof import('./src/components/gismap.vue')['default']
    Help: typeof import('./src/components/help.vue')['default']
    HomeDefault: typeof import('./src/components/homeDefault.vue')['default']
    Homenavbar: typeof import('./src/components/homenavbar.vue')['default']
    LoginMode: typeof import('./src/components/loginMode.vue')['default']
    LoginOtherForm: typeof import('./src/components/loginOtherForm.vue')['default']
    NowDatetime: typeof import('./src/components/nowDatetime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings.vue')['default']
    SwiperBack: typeof import('./src/components/swiperBack.vue')['default']
  }
}
